version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
# new SperServer Port
#      - 51773
      - 1972
      - 52773
      - 53773
    volumes:
# no license required for community edition
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
